// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: dbus.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DbusUbitUploader_DbusUnitUpload_FullMethodName = "/dbus.DbusUbitUploader/DbusUnitUpload"
)

// DbusUbitUploaderClient is the client API for DbusUbitUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbusUbitUploaderClient interface {
	DbusUnitUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DbusUnitLog, DbusUnitAck], error)
}

type dbusUbitUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDbusUbitUploaderClient(cc grpc.ClientConnInterface) DbusUbitUploaderClient {
	return &dbusUbitUploaderClient{cc}
}

func (c *dbusUbitUploaderClient) DbusUnitUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DbusUnitLog, DbusUnitAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DbusUbitUploader_ServiceDesc.Streams[0], DbusUbitUploader_DbusUnitUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DbusUnitLog, DbusUnitAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DbusUbitUploader_DbusUnitUploadClient = grpc.ClientStreamingClient[DbusUnitLog, DbusUnitAck]

// DbusUbitUploaderServer is the server API for DbusUbitUploader service.
// All implementations must embed UnimplementedDbusUbitUploaderServer
// for forward compatibility.
type DbusUbitUploaderServer interface {
	DbusUnitUpload(grpc.ClientStreamingServer[DbusUnitLog, DbusUnitAck]) error
	mustEmbedUnimplementedDbusUbitUploaderServer()
}

// UnimplementedDbusUbitUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbusUbitUploaderServer struct{}

func (UnimplementedDbusUbitUploaderServer) DbusUnitUpload(grpc.ClientStreamingServer[DbusUnitLog, DbusUnitAck]) error {
	return status.Error(codes.Unimplemented, "method DbusUnitUpload not implemented")
}
func (UnimplementedDbusUbitUploaderServer) mustEmbedUnimplementedDbusUbitUploaderServer() {}
func (UnimplementedDbusUbitUploaderServer) testEmbeddedByValue()                          {}

// UnsafeDbusUbitUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbusUbitUploaderServer will
// result in compilation errors.
type UnsafeDbusUbitUploaderServer interface {
	mustEmbedUnimplementedDbusUbitUploaderServer()
}

func RegisterDbusUbitUploaderServer(s grpc.ServiceRegistrar, srv DbusUbitUploaderServer) {
	// If the following call panics, it indicates UnimplementedDbusUbitUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DbusUbitUploader_ServiceDesc, srv)
}

func _DbusUbitUploader_DbusUnitUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DbusUbitUploaderServer).DbusUnitUpload(&grpc.GenericServerStream[DbusUnitLog, DbusUnitAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DbusUbitUploader_DbusUnitUploadServer = grpc.ClientStreamingServer[DbusUnitLog, DbusUnitAck]

// DbusUbitUploader_ServiceDesc is the grpc.ServiceDesc for DbusUbitUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbusUbitUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbus.DbusUbitUploader",
	HandlerType: (*DbusUbitUploaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DbusUnitUpload",
			Handler:       _DbusUbitUploader_DbusUnitUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dbus.proto",
}
