// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dbus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DbusUnitLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LoadState     string                 `protobuf:"bytes,3,opt,name=loadState,proto3" json:"loadState,omitempty"`
	ActiveState   string                 `protobuf:"bytes,4,opt,name=activeState,proto3" json:"activeState,omitempty"`
	SubState      string                 `protobuf:"bytes,5,opt,name=subState,proto3" json:"subState,omitempty"`
	Followed      string                 `protobuf:"bytes,6,opt,name=followed,proto3" json:"followed,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	JobId         uint32                 `protobuf:"varint,8,opt,name=jobId,proto3" json:"jobId,omitempty"`
	JobType       string                 `protobuf:"bytes,9,opt,name=jobType,proto3" json:"jobType,omitempty"`
	JobPath       string                 `protobuf:"bytes,10,opt,name=jobPath,proto3" json:"jobPath,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbusUnitLog) Reset() {
	*x = DbusUnitLog{}
	mi := &file_dbus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbusUnitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbusUnitLog) ProtoMessage() {}

func (x *DbusUnitLog) ProtoReflect() protoreflect.Message {
	mi := &file_dbus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbusUnitLog.ProtoReflect.Descriptor instead.
func (*DbusUnitLog) Descriptor() ([]byte, []int) {
	return file_dbus_proto_rawDescGZIP(), []int{0}
}

func (x *DbusUnitLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DbusUnitLog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DbusUnitLog) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *DbusUnitLog) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *DbusUnitLog) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *DbusUnitLog) GetFollowed() string {
	if x != nil {
		return x.Followed
	}
	return ""
}

func (x *DbusUnitLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DbusUnitLog) GetJobId() uint32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *DbusUnitLog) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *DbusUnitLog) GetJobPath() string {
	if x != nil {
		return x.JobPath
	}
	return ""
}

func (x *DbusUnitLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DbusUnitAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int64                  `protobuf:"varint,1,opt,name=totalChunks,proto3" json:"totalChunks,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbusUnitAck) Reset() {
	*x = DbusUnitAck{}
	mi := &file_dbus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbusUnitAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbusUnitAck) ProtoMessage() {}

func (x *DbusUnitAck) ProtoReflect() protoreflect.Message {
	mi := &file_dbus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbusUnitAck.ProtoReflect.Descriptor instead.
func (*DbusUnitAck) Descriptor() ([]byte, []int) {
	return file_dbus_proto_rawDescGZIP(), []int{1}
}

func (x *DbusUnitAck) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *DbusUnitAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_dbus_proto protoreflect.FileDescriptor

const file_dbus_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dbus.proto\x12\x04dbus\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x02\n" +
	"\vDbusUnitLog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tloadState\x18\x03 \x01(\tR\tloadState\x12 \n" +
	"\vactiveState\x18\x04 \x01(\tR\vactiveState\x12\x1a\n" +
	"\bsubState\x18\x05 \x01(\tR\bsubState\x12\x1a\n" +
	"\bfollowed\x18\x06 \x01(\tR\bfollowed\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x14\n" +
	"\x05jobId\x18\b \x01(\rR\x05jobId\x12\x18\n" +
	"\ajobType\x18\t \x01(\tR\ajobType\x12\x18\n" +
	"\ajobPath\x18\n" +
	" \x01(\tR\ajobPath\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"I\n" +
	"\vDbusUnitAck\x12 \n" +
	"\vtotalChunks\x18\x01 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2L\n" +
	"\x10DbusUbitUploader\x128\n" +
	"\x0eDbusUnitUpload\x12\x11.dbus.DbusUnitLog\x1a\x11.dbus.DbusUnitAck(\x01B\"Z github.com/incodi404/logintel/pbb\x06proto3"

var (
	file_dbus_proto_rawDescOnce sync.Once
	file_dbus_proto_rawDescData []byte
)

func file_dbus_proto_rawDescGZIP() []byte {
	file_dbus_proto_rawDescOnce.Do(func() {
		file_dbus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbus_proto_rawDesc), len(file_dbus_proto_rawDesc)))
	})
	return file_dbus_proto_rawDescData
}

var file_dbus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dbus_proto_goTypes = []any{
	(*DbusUnitLog)(nil),           // 0: dbus.DbusUnitLog
	(*DbusUnitAck)(nil),           // 1: dbus.DbusUnitAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_dbus_proto_depIdxs = []int32{
	2, // 0: dbus.DbusUnitLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: dbus.DbusUbitUploader.DbusUnitUpload:input_type -> dbus.DbusUnitLog
	1, // 2: dbus.DbusUbitUploader.DbusUnitUpload:output_type -> dbus.DbusUnitAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dbus_proto_init() }
func file_dbus_proto_init() {
	if File_dbus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbus_proto_rawDesc), len(file_dbus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbus_proto_goTypes,
		DependencyIndexes: file_dbus_proto_depIdxs,
		MessageInfos:      file_dbus_proto_msgTypes,
	}.Build()
	File_dbus_proto = out.File
	file_dbus_proto_goTypes = nil
	file_dbus_proto_depIdxs = nil
}
