// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: execve.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecveLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	ParentProcess int64                  `protobuf:"varint,4,opt,name=parent_process,json=parentProcess,proto3" json:"parent_process,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentId       string                 `protobuf:"bytes,6,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecveLog) Reset() {
	*x = ExecveLog{}
	mi := &file_execve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecveLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecveLog) ProtoMessage() {}

func (x *ExecveLog) ProtoReflect() protoreflect.Message {
	mi := &file_execve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecveLog.ProtoReflect.Descriptor instead.
func (*ExecveLog) Descriptor() ([]byte, []int) {
	return file_execve_proto_rawDescGZIP(), []int{0}
}

func (x *ExecveLog) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecveLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecveLog) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ExecveLog) GetParentProcess() int64 {
	if x != nil {
		return x.ParentProcess
	}
	return 0
}

func (x *ExecveLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecveLog) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ExecveAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecveAck) Reset() {
	*x = ExecveAck{}
	mi := &file_execve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecveAck) ProtoMessage() {}

func (x *ExecveAck) ProtoReflect() protoreflect.Message {
	mi := &file_execve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecveAck.ProtoReflect.Descriptor instead.
func (*ExecveAck) Descriptor() ([]byte, []int) {
	return file_execve_proto_rawDescGZIP(), []int{1}
}

func (x *ExecveAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecveAck) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

var File_execve_proto protoreflect.FileDescriptor

const file_execve_proto_rawDesc = "" +
	"\n" +
	"\fexecve.proto\x12\x06execve\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\tExecveLog\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12%\n" +
	"\x0eparent_process\x18\x04 \x01(\x03R\rparentProcess\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aagentId\x18\x06 \x01(\tR\aagentId\"H\n" +
	"\tExecveAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x03R\vtotalChunks2K\n" +
	"\x11ExecveLogUploader\x126\n" +
	"\fExecveUpload\x12\x11.execve.ExecveLog\x1a\x11.execve.ExecveAck(\x01B\"Z github.com/incodi404/logintel/pbb\x06proto3"

var (
	file_execve_proto_rawDescOnce sync.Once
	file_execve_proto_rawDescData []byte
)

func file_execve_proto_rawDescGZIP() []byte {
	file_execve_proto_rawDescOnce.Do(func() {
		file_execve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execve_proto_rawDesc), len(file_execve_proto_rawDesc)))
	})
	return file_execve_proto_rawDescData
}

var file_execve_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_execve_proto_goTypes = []any{
	(*ExecveLog)(nil),             // 0: execve.ExecveLog
	(*ExecveAck)(nil),             // 1: execve.ExecveAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_execve_proto_depIdxs = []int32{
	2, // 0: execve.ExecveLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: execve.ExecveLogUploader.ExecveUpload:input_type -> execve.ExecveLog
	1, // 2: execve.ExecveLogUploader.ExecveUpload:output_type -> execve.ExecveAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_execve_proto_init() }
func file_execve_proto_init() {
	if File_execve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execve_proto_rawDesc), len(file_execve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execve_proto_goTypes,
		DependencyIndexes: file_execve_proto_depIdxs,
		MessageInfos:      file_execve_proto_msgTypes,
	}.Build()
	File_execve_proto = out.File
	file_execve_proto_goTypes = nil
	file_execve_proto_depIdxs = nil
}
