// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: exec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// client-side data
type ExecLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OldPid        uint32                 `protobuf:"varint,3,opt,name=old_pid,json=oldPid,proto3" json:"old_pid,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Comm          string                 `protobuf:"bytes,5,opt,name=comm,proto3" json:"comm,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecLog) Reset() {
	*x = ExecLog{}
	mi := &file_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecLog) ProtoMessage() {}

func (x *ExecLog) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecLog.ProtoReflect.Descriptor instead.
func (*ExecLog) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecLog) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExecLog) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecLog) GetOldPid() uint32 {
	if x != nil {
		return x.OldPid
	}
	return 0
}

func (x *ExecLog) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ExecLog) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ExecLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// server side
type ExecAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TotalChunks   int64                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecAck) Reset() {
	*x = ExecAck{}
	mi := &file_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecAck) ProtoMessage() {}

func (x *ExecAck) ProtoReflect() protoreflect.Message {
	mi := &file_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecAck.ProtoReflect.Descriptor instead.
func (*ExecAck) Descriptor() ([]byte, []int) {
	return file_exec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecAck) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

var File_exec_proto protoreflect.FileDescriptor

const file_exec_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exec.proto\x12\x04exec\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\aExecLog\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x17\n" +
	"\aold_pid\x18\x03 \x01(\rR\x06oldPid\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x12\n" +
	"\x04comm\x18\x05 \x01(\tR\x04comm\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"F\n" +
	"\aExecAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x03R\vtotalChunks2?\n" +
	"\x0fExecLogUploader\x12,\n" +
	"\n" +
	"ExecUpload\x12\r.exec.ExecLog\x1a\r.exec.ExecAck(\x01B\"Z github.com/incodi404/logintel/pbb\x06proto3"

var (
	file_exec_proto_rawDescOnce sync.Once
	file_exec_proto_rawDescData []byte
)

func file_exec_proto_rawDescGZIP() []byte {
	file_exec_proto_rawDescOnce.Do(func() {
		file_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)))
	})
	return file_exec_proto_rawDescData
}

var file_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exec_proto_goTypes = []any{
	(*ExecLog)(nil),               // 0: exec.ExecLog
	(*ExecAck)(nil),               // 1: exec.ExecAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_exec_proto_depIdxs = []int32{
	2, // 0: exec.ExecLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: exec.ExecLogUploader.ExecUpload:input_type -> exec.ExecLog
	1, // 2: exec.ExecLogUploader.ExecUpload:output_type -> exec.ExecAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exec_proto_init() }
func file_exec_proto_init() {
	if File_exec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exec_proto_rawDesc), len(file_exec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exec_proto_goTypes,
		DependencyIndexes: file_exec_proto_depIdxs,
		MessageInfos:      file_exec_proto_msgTypes,
	}.Build()
	File_exec_proto = out.File
	file_exec_proto_goTypes = nil
	file_exec_proto_depIdxs = nil
}
