// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: execve.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecveLogUploader_ExecveUpload_FullMethodName = "/execve.ExecveLogUploader/ExecveUpload"
)

// ExecveLogUploaderClient is the client API for ExecveLogUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecveLogUploaderClient interface {
	ExecveUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecveLog, ExecveAck], error)
}

type execveLogUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewExecveLogUploaderClient(cc grpc.ClientConnInterface) ExecveLogUploaderClient {
	return &execveLogUploaderClient{cc}
}

func (c *execveLogUploaderClient) ExecveUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecveLog, ExecveAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecveLogUploader_ServiceDesc.Streams[0], ExecveLogUploader_ExecveUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecveLog, ExecveAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecveLogUploader_ExecveUploadClient = grpc.ClientStreamingClient[ExecveLog, ExecveAck]

// ExecveLogUploaderServer is the server API for ExecveLogUploader service.
// All implementations must embed UnimplementedExecveLogUploaderServer
// for forward compatibility.
type ExecveLogUploaderServer interface {
	ExecveUpload(grpc.ClientStreamingServer[ExecveLog, ExecveAck]) error
	mustEmbedUnimplementedExecveLogUploaderServer()
}

// UnimplementedExecveLogUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecveLogUploaderServer struct{}

func (UnimplementedExecveLogUploaderServer) ExecveUpload(grpc.ClientStreamingServer[ExecveLog, ExecveAck]) error {
	return status.Error(codes.Unimplemented, "method ExecveUpload not implemented")
}
func (UnimplementedExecveLogUploaderServer) mustEmbedUnimplementedExecveLogUploaderServer() {}
func (UnimplementedExecveLogUploaderServer) testEmbeddedByValue()                           {}

// UnsafeExecveLogUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecveLogUploaderServer will
// result in compilation errors.
type UnsafeExecveLogUploaderServer interface {
	mustEmbedUnimplementedExecveLogUploaderServer()
}

func RegisterExecveLogUploaderServer(s grpc.ServiceRegistrar, srv ExecveLogUploaderServer) {
	// If the following call panics, it indicates UnimplementedExecveLogUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecveLogUploader_ServiceDesc, srv)
}

func _ExecveLogUploader_ExecveUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecveLogUploaderServer).ExecveUpload(&grpc.GenericServerStream[ExecveLog, ExecveAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecveLogUploader_ExecveUploadServer = grpc.ClientStreamingServer[ExecveLog, ExecveAck]

// ExecveLogUploader_ServiceDesc is the grpc.ServiceDesc for ExecveLogUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecveLogUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execve.ExecveLogUploader",
	HandlerType: (*ExecveLogUploaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecveUpload",
			Handler:       _ExecveLogUploader_ExecveUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "execve.proto",
}
