// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: exec.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecLogUploader_ExecUpload_FullMethodName = "/exec.ExecLogUploader/ExecUpload"
)

// ExecLogUploaderClient is the client API for ExecLogUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecLogUploaderClient interface {
	ExecUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecLog, ExecAck], error)
}

type execLogUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewExecLogUploaderClient(cc grpc.ClientConnInterface) ExecLogUploaderClient {
	return &execLogUploaderClient{cc}
}

func (c *execLogUploaderClient) ExecUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ExecLog, ExecAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecLogUploader_ServiceDesc.Streams[0], ExecLogUploader_ExecUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecLog, ExecAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecLogUploader_ExecUploadClient = grpc.ClientStreamingClient[ExecLog, ExecAck]

// ExecLogUploaderServer is the server API for ExecLogUploader service.
// All implementations must embed UnimplementedExecLogUploaderServer
// for forward compatibility.
type ExecLogUploaderServer interface {
	ExecUpload(grpc.ClientStreamingServer[ExecLog, ExecAck]) error
	mustEmbedUnimplementedExecLogUploaderServer()
}

// UnimplementedExecLogUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecLogUploaderServer struct{}

func (UnimplementedExecLogUploaderServer) ExecUpload(grpc.ClientStreamingServer[ExecLog, ExecAck]) error {
	return status.Error(codes.Unimplemented, "method ExecUpload not implemented")
}
func (UnimplementedExecLogUploaderServer) mustEmbedUnimplementedExecLogUploaderServer() {}
func (UnimplementedExecLogUploaderServer) testEmbeddedByValue()                         {}

// UnsafeExecLogUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecLogUploaderServer will
// result in compilation errors.
type UnsafeExecLogUploaderServer interface {
	mustEmbedUnimplementedExecLogUploaderServer()
}

func RegisterExecLogUploaderServer(s grpc.ServiceRegistrar, srv ExecLogUploaderServer) {
	// If the following call panics, it indicates UnimplementedExecLogUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecLogUploader_ServiceDesc, srv)
}

func _ExecLogUploader_ExecUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecLogUploaderServer).ExecUpload(&grpc.GenericServerStream[ExecLog, ExecAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecLogUploader_ExecUploadServer = grpc.ClientStreamingServer[ExecLog, ExecAck]

// ExecLogUploader_ServiceDesc is the grpc.ServiceDesc for ExecLogUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecLogUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exec.ExecLogUploader",
	HandlerType: (*ExecLogUploaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecUpload",
			Handler:       _ExecLogUploader_ExecUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "exec.proto",
}
