// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fanotify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FanotifyLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int64                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	ParentProcess int64                  `protobuf:"varint,4,opt,name=parent_process,json=parentProcess,proto3" json:"parent_process,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Events        []string               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanotifyLog) Reset() {
	*x = FanotifyLog{}
	mi := &file_fanotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanotifyLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanotifyLog) ProtoMessage() {}

func (x *FanotifyLog) ProtoReflect() protoreflect.Message {
	mi := &file_fanotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanotifyLog.ProtoReflect.Descriptor instead.
func (*FanotifyLog) Descriptor() ([]byte, []int) {
	return file_fanotify_proto_rawDescGZIP(), []int{0}
}

func (x *FanotifyLog) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FanotifyLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FanotifyLog) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *FanotifyLog) GetParentProcess() int64 {
	if x != nil {
		return x.ParentProcess
	}
	return 0
}

func (x *FanotifyLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FanotifyLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FanotifyLog) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type FanotifyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int64                  `protobuf:"varint,1,opt,name=totalChunks,proto3" json:"totalChunks,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanotifyAck) Reset() {
	*x = FanotifyAck{}
	mi := &file_fanotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanotifyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanotifyAck) ProtoMessage() {}

func (x *FanotifyAck) ProtoReflect() protoreflect.Message {
	mi := &file_fanotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanotifyAck.ProtoReflect.Descriptor instead.
func (*FanotifyAck) Descriptor() ([]byte, []int) {
	return file_fanotify_proto_rawDescGZIP(), []int{1}
}

func (x *FanotifyAck) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *FanotifyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fanotify_proto protoreflect.FileDescriptor

const file_fanotify_proto_rawDesc = "" +
	"\n" +
	"\x0efanotify.proto\x12\bfanotify\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\vFanotifyLog\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x03R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12%\n" +
	"\x0eparent_process\x18\x04 \x01(\x03R\rparentProcess\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\"I\n" +
	"\vFanotifyAck\x12 \n" +
	"\vtotalChunks\x18\x01 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2T\n" +
	"\x10FanotifyUploader\x12@\n" +
	"\x0eFanotifyUpload\x12\x15.fanotify.FanotifyLog\x1a\x15.fanotify.FanotifyAck(\x01B\"Z github.com/incodi404/logintel/pbb\x06proto3"

var (
	file_fanotify_proto_rawDescOnce sync.Once
	file_fanotify_proto_rawDescData []byte
)

func file_fanotify_proto_rawDescGZIP() []byte {
	file_fanotify_proto_rawDescOnce.Do(func() {
		file_fanotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fanotify_proto_rawDesc), len(file_fanotify_proto_rawDesc)))
	})
	return file_fanotify_proto_rawDescData
}

var file_fanotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fanotify_proto_goTypes = []any{
	(*FanotifyLog)(nil),           // 0: fanotify.FanotifyLog
	(*FanotifyAck)(nil),           // 1: fanotify.FanotifyAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_fanotify_proto_depIdxs = []int32{
	2, // 0: fanotify.FanotifyLog.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: fanotify.FanotifyUploader.FanotifyUpload:input_type -> fanotify.FanotifyLog
	1, // 2: fanotify.FanotifyUploader.FanotifyUpload:output_type -> fanotify.FanotifyAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fanotify_proto_init() }
func file_fanotify_proto_init() {
	if File_fanotify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fanotify_proto_rawDesc), len(file_fanotify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fanotify_proto_goTypes,
		DependencyIndexes: file_fanotify_proto_depIdxs,
		MessageInfos:      file_fanotify_proto_msgTypes,
	}.Build()
	File_fanotify_proto = out.File
	file_fanotify_proto_goTypes = nil
	file_fanotify_proto_depIdxs = nil
}
