// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: network.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ISSSLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldState      string                 `protobuf:"bytes,1,opt,name=oldState,proto3" json:"oldState,omitempty"`
	NewState      string                 `protobuf:"bytes,2,opt,name=newState,proto3" json:"newState,omitempty"`
	SPort         uint32                 `protobuf:"varint,3,opt,name=sPort,proto3" json:"sPort,omitempty"`
	DPort         uint32                 `protobuf:"varint,4,opt,name=dPort,proto3" json:"dPort,omitempty"`
	Family        string                 `protobuf:"bytes,5,opt,name=family,proto3" json:"family,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SAddr         string                 `protobuf:"bytes,7,opt,name=sAddr,proto3" json:"sAddr,omitempty"`
	DAddr         string                 `protobuf:"bytes,8,opt,name=dAddr,proto3" json:"dAddr,omitempty"`
	Pid           int64                  `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,11,opt,name=comm,proto3" json:"comm,omitempty"`
	ParentProcess int64                  `protobuf:"varint,12,opt,name=parent_process,json=parentProcess,proto3" json:"parent_process,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISSSLog) Reset() {
	*x = ISSSLog{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISSSLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISSSLog) ProtoMessage() {}

func (x *ISSSLog) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISSSLog.ProtoReflect.Descriptor instead.
func (*ISSSLog) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *ISSSLog) GetOldState() string {
	if x != nil {
		return x.OldState
	}
	return ""
}

func (x *ISSSLog) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *ISSSLog) GetSPort() uint32 {
	if x != nil {
		return x.SPort
	}
	return 0
}

func (x *ISSSLog) GetDPort() uint32 {
	if x != nil {
		return x.DPort
	}
	return 0
}

func (x *ISSSLog) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *ISSSLog) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ISSSLog) GetSAddr() string {
	if x != nil {
		return x.SAddr
	}
	return ""
}

func (x *ISSSLog) GetDAddr() string {
	if x != nil {
		return x.DAddr
	}
	return ""
}

func (x *ISSSLog) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ISSSLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ISSSLog) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ISSSLog) GetParentProcess() int64 {
	if x != nil {
		return x.ParentProcess
	}
	return 0
}

func (x *ISSSLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Connect4Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFamily    string                 `protobuf:"bytes,1,opt,name=userFamily,proto3" json:"userFamily,omitempty"`
	UserIPv4      string                 `protobuf:"bytes,2,opt,name=userIPv4,proto3" json:"userIPv4,omitempty"`
	UserPort      uint32                 `protobuf:"varint,3,opt,name=userPort,proto3" json:"userPort,omitempty"`
	Family        string                 `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Uid           uint32                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pid           int64                  `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,11,opt,name=comm,proto3" json:"comm,omitempty"`
	ParentProcess int64                  `protobuf:"varint,12,opt,name=parent_process,json=parentProcess,proto3" json:"parent_process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect4Log) Reset() {
	*x = Connect4Log{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect4Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect4Log) ProtoMessage() {}

func (x *Connect4Log) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect4Log.ProtoReflect.Descriptor instead.
func (*Connect4Log) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *Connect4Log) GetUserFamily() string {
	if x != nil {
		return x.UserFamily
	}
	return ""
}

func (x *Connect4Log) GetUserIPv4() string {
	if x != nil {
		return x.UserIPv4
	}
	return ""
}

func (x *Connect4Log) GetUserPort() uint32 {
	if x != nil {
		return x.UserPort
	}
	return 0
}

func (x *Connect4Log) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Connect4Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Connect4Log) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Connect4Log) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Connect4Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Connect4Log) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Connect4Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Connect4Log) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Connect4Log) GetParentProcess() int64 {
	if x != nil {
		return x.ParentProcess
	}
	return 0
}

type Bind4Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFamily    string                 `protobuf:"bytes,1,opt,name=userFamily,proto3" json:"userFamily,omitempty"`
	UserIPv4      string                 `protobuf:"bytes,2,opt,name=userIPv4,proto3" json:"userIPv4,omitempty"`
	UserPort      uint32                 `protobuf:"varint,3,opt,name=userPort,proto3" json:"userPort,omitempty"`
	Family        string                 `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Uid           uint32                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pid           int64                  `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Comm          string                 `protobuf:"bytes,11,opt,name=comm,proto3" json:"comm,omitempty"`
	ParentProcess int64                  `protobuf:"varint,12,opt,name=parent_process,json=parentProcess,proto3" json:"parent_process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bind4Log) Reset() {
	*x = Bind4Log{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bind4Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bind4Log) ProtoMessage() {}

func (x *Bind4Log) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bind4Log.ProtoReflect.Descriptor instead.
func (*Bind4Log) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *Bind4Log) GetUserFamily() string {
	if x != nil {
		return x.UserFamily
	}
	return ""
}

func (x *Bind4Log) GetUserIPv4() string {
	if x != nil {
		return x.UserIPv4
	}
	return ""
}

func (x *Bind4Log) GetUserPort() uint32 {
	if x != nil {
		return x.UserPort
	}
	return 0
}

func (x *Bind4Log) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Bind4Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bind4Log) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Bind4Log) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Bind4Log) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Bind4Log) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Bind4Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bind4Log) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *Bind4Log) GetParentProcess() int64 {
	if x != nil {
		return x.ParentProcess
	}
	return 0
}

type ISSSAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int64                  `protobuf:"varint,1,opt,name=totalChunks,proto3" json:"totalChunks,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISSSAck) Reset() {
	*x = ISSSAck{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISSSAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISSSAck) ProtoMessage() {}

func (x *ISSSAck) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISSSAck.ProtoReflect.Descriptor instead.
func (*ISSSAck) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *ISSSAck) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *ISSSAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Connect4Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int64                  `protobuf:"varint,1,opt,name=totalChunks,proto3" json:"totalChunks,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect4Ack) Reset() {
	*x = Connect4Ack{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect4Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect4Ack) ProtoMessage() {}

func (x *Connect4Ack) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect4Ack.ProtoReflect.Descriptor instead.
func (*Connect4Ack) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *Connect4Ack) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *Connect4Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Bind4Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   int64                  `protobuf:"varint,1,opt,name=totalChunks,proto3" json:"totalChunks,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bind4Ack) Reset() {
	*x = Bind4Ack{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bind4Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bind4Ack) ProtoMessage() {}

func (x *Bind4Ack) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bind4Ack.ProtoReflect.Descriptor instead.
func (*Bind4Ack) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *Bind4Ack) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *Bind4Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\anetwork\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\aISSSLog\x12\x1a\n" +
	"\boldState\x18\x01 \x01(\tR\boldState\x12\x1a\n" +
	"\bnewState\x18\x02 \x01(\tR\bnewState\x12\x14\n" +
	"\x05sPort\x18\x03 \x01(\rR\x05sPort\x12\x14\n" +
	"\x05dPort\x18\x04 \x01(\rR\x05dPort\x12\x16\n" +
	"\x06family\x18\x05 \x01(\tR\x06family\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05sAddr\x18\a \x01(\tR\x05sAddr\x12\x14\n" +
	"\x05dAddr\x18\b \x01(\tR\x05dAddr\x12\x10\n" +
	"\x03pid\x18\t \x01(\x03R\x03pid\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\v \x01(\tR\x04comm\x12%\n" +
	"\x0eparent_process\x18\f \x01(\x03R\rparentProcess\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xda\x02\n" +
	"\vConnect4Log\x12\x1e\n" +
	"\n" +
	"userFamily\x18\x01 \x01(\tR\n" +
	"userFamily\x12\x1a\n" +
	"\buserIPv4\x18\x02 \x01(\tR\buserIPv4\x12\x1a\n" +
	"\buserPort\x18\x03 \x01(\rR\buserPort\x12\x16\n" +
	"\x06family\x18\x04 \x01(\tR\x06family\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03uid\x18\a \x01(\rR\x03uid\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03pid\x18\t \x01(\x03R\x03pid\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\v \x01(\tR\x04comm\x12%\n" +
	"\x0eparent_process\x18\f \x01(\x03R\rparentProcess\"\xd7\x02\n" +
	"\bBind4Log\x12\x1e\n" +
	"\n" +
	"userFamily\x18\x01 \x01(\tR\n" +
	"userFamily\x12\x1a\n" +
	"\buserIPv4\x18\x02 \x01(\tR\buserIPv4\x12\x1a\n" +
	"\buserPort\x18\x03 \x01(\rR\buserPort\x12\x16\n" +
	"\x06family\x18\x04 \x01(\tR\x06family\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03uid\x18\a \x01(\rR\x03uid\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03pid\x18\t \x01(\x03R\x03pid\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04comm\x18\v \x01(\tR\x04comm\x12%\n" +
	"\x0eparent_process\x18\f \x01(\x03R\rparentProcess\"E\n" +
	"\aISSSAck\x12 \n" +
	"\vtotalChunks\x18\x01 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\vConnect4Ack\x12 \n" +
	"\vtotalChunks\x18\x01 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\bBind4Ack\x12 \n" +
	"\vtotalChunks\x18\x01 \x01(\x03R\vtotalChunks\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbf\x01\n" +
	"\x12NetworkLogUploader\x122\n" +
	"\n" +
	"ISSSUpload\x12\x10.network.ISSSLog\x1a\x10.network.ISSSAck(\x01\x12>\n" +
	"\x0eConnect4Upload\x12\x14.network.Connect4Log\x1a\x14.network.Connect4Ack(\x01\x125\n" +
	"\vBind4Upload\x12\x11.network.Bind4Log\x1a\x11.network.Bind4Ack(\x01B\"Z github.com/incodi404/logintel/pbb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_network_proto_goTypes = []any{
	(*ISSSLog)(nil),               // 0: network.ISSSLog
	(*Connect4Log)(nil),           // 1: network.Connect4Log
	(*Bind4Log)(nil),              // 2: network.Bind4Log
	(*ISSSAck)(nil),               // 3: network.ISSSAck
	(*Connect4Ack)(nil),           // 4: network.Connect4Ack
	(*Bind4Ack)(nil),              // 5: network.Bind4Ack
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_network_proto_depIdxs = []int32{
	6, // 0: network.ISSSLog.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: network.Connect4Log.timestamp:type_name -> google.protobuf.Timestamp
	6, // 2: network.Bind4Log.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: network.NetworkLogUploader.ISSSUpload:input_type -> network.ISSSLog
	1, // 4: network.NetworkLogUploader.Connect4Upload:input_type -> network.Connect4Log
	2, // 5: network.NetworkLogUploader.Bind4Upload:input_type -> network.Bind4Log
	3, // 6: network.NetworkLogUploader.ISSSUpload:output_type -> network.ISSSAck
	4, // 7: network.NetworkLogUploader.Connect4Upload:output_type -> network.Connect4Ack
	5, // 8: network.NetworkLogUploader.Bind4Upload:output_type -> network.Bind4Ack
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
