// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: network.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkLogUploader_ISSSUpload_FullMethodName     = "/network.NetworkLogUploader/ISSSUpload"
	NetworkLogUploader_Connect4Upload_FullMethodName = "/network.NetworkLogUploader/Connect4Upload"
	NetworkLogUploader_Bind4Upload_FullMethodName    = "/network.NetworkLogUploader/Bind4Upload"
)

// NetworkLogUploaderClient is the client API for NetworkLogUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkLogUploaderClient interface {
	ISSSUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ISSSLog, ISSSAck], error)
	Connect4Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Connect4Log, Connect4Ack], error)
	Bind4Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Bind4Log, Bind4Ack], error)
}

type networkLogUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkLogUploaderClient(cc grpc.ClientConnInterface) NetworkLogUploaderClient {
	return &networkLogUploaderClient{cc}
}

func (c *networkLogUploaderClient) ISSSUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ISSSLog, ISSSAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkLogUploader_ServiceDesc.Streams[0], NetworkLogUploader_ISSSUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ISSSLog, ISSSAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_ISSSUploadClient = grpc.ClientStreamingClient[ISSSLog, ISSSAck]

func (c *networkLogUploaderClient) Connect4Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Connect4Log, Connect4Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkLogUploader_ServiceDesc.Streams[1], NetworkLogUploader_Connect4Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Connect4Log, Connect4Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_Connect4UploadClient = grpc.ClientStreamingClient[Connect4Log, Connect4Ack]

func (c *networkLogUploaderClient) Bind4Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Bind4Log, Bind4Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NetworkLogUploader_ServiceDesc.Streams[2], NetworkLogUploader_Bind4Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Bind4Log, Bind4Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_Bind4UploadClient = grpc.ClientStreamingClient[Bind4Log, Bind4Ack]

// NetworkLogUploaderServer is the server API for NetworkLogUploader service.
// All implementations must embed UnimplementedNetworkLogUploaderServer
// for forward compatibility.
type NetworkLogUploaderServer interface {
	ISSSUpload(grpc.ClientStreamingServer[ISSSLog, ISSSAck]) error
	Connect4Upload(grpc.ClientStreamingServer[Connect4Log, Connect4Ack]) error
	Bind4Upload(grpc.ClientStreamingServer[Bind4Log, Bind4Ack]) error
	mustEmbedUnimplementedNetworkLogUploaderServer()
}

// UnimplementedNetworkLogUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkLogUploaderServer struct{}

func (UnimplementedNetworkLogUploaderServer) ISSSUpload(grpc.ClientStreamingServer[ISSSLog, ISSSAck]) error {
	return status.Error(codes.Unimplemented, "method ISSSUpload not implemented")
}
func (UnimplementedNetworkLogUploaderServer) Connect4Upload(grpc.ClientStreamingServer[Connect4Log, Connect4Ack]) error {
	return status.Error(codes.Unimplemented, "method Connect4Upload not implemented")
}
func (UnimplementedNetworkLogUploaderServer) Bind4Upload(grpc.ClientStreamingServer[Bind4Log, Bind4Ack]) error {
	return status.Error(codes.Unimplemented, "method Bind4Upload not implemented")
}
func (UnimplementedNetworkLogUploaderServer) mustEmbedUnimplementedNetworkLogUploaderServer() {}
func (UnimplementedNetworkLogUploaderServer) testEmbeddedByValue()                            {}

// UnsafeNetworkLogUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkLogUploaderServer will
// result in compilation errors.
type UnsafeNetworkLogUploaderServer interface {
	mustEmbedUnimplementedNetworkLogUploaderServer()
}

func RegisterNetworkLogUploaderServer(s grpc.ServiceRegistrar, srv NetworkLogUploaderServer) {
	// If the following call panics, it indicates UnimplementedNetworkLogUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkLogUploader_ServiceDesc, srv)
}

func _NetworkLogUploader_ISSSUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkLogUploaderServer).ISSSUpload(&grpc.GenericServerStream[ISSSLog, ISSSAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_ISSSUploadServer = grpc.ClientStreamingServer[ISSSLog, ISSSAck]

func _NetworkLogUploader_Connect4Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkLogUploaderServer).Connect4Upload(&grpc.GenericServerStream[Connect4Log, Connect4Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_Connect4UploadServer = grpc.ClientStreamingServer[Connect4Log, Connect4Ack]

func _NetworkLogUploader_Bind4Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NetworkLogUploaderServer).Bind4Upload(&grpc.GenericServerStream[Bind4Log, Bind4Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NetworkLogUploader_Bind4UploadServer = grpc.ClientStreamingServer[Bind4Log, Bind4Ack]

// NetworkLogUploader_ServiceDesc is the grpc.ServiceDesc for NetworkLogUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkLogUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.NetworkLogUploader",
	HandlerType: (*NetworkLogUploaderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ISSSUpload",
			Handler:       _NetworkLogUploader_ISSSUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Connect4Upload",
			Handler:       _NetworkLogUploader_Connect4Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Bind4Upload",
			Handler:       _NetworkLogUploader_Bind4Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "network.proto",
}
